config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root :to => 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.save
    redirect_to post_path(post.id)
  end

  def index
    @posts = Post.all
  end

  def show 
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:location, :text, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/top.html.erb
<div class="cover alin-middle">
    <div class="text-center">
        <p class="sub-title">～旅行の思い出を共有する～</p>
        <h1 class="title mb-2">Traveler</h1>
        <h2 class="btn btn-primary mr-2">新規登録</h2>
        <h2 class="btn btn-success ml-2">ログイン</h2>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traveler</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="cover-edit">
    <div class="container">
        <div class="row">
            <h1 class="font-weight-normal mt-5 mb-5">旅行投稿編集</h1>
        </div>
        <div class="row">
            <%= form_with model: @post, local: true do |f| %>
                <div class="form-group mb-3">
                    <label class="form-label">旅行先</label>
                    <%= f.text_field :location, class: "form-control" %>
                </div>
                <div class="form-group mb-3">
                    <label class="form-label">感想</label>
                    <%= f.text_area :text ,rows: 10, class: "form-control" %>
                </div>
                <div class="form-group mb-4">
                    <label class="form-label">画像</label><br>
                    <% if @post.image.attached? %>
                        <%= image_tag @post.image.variant(resize_to_limit: [450,350]) %><br>
                    <% end %>
                    <label class="form-label">画像を変更する</label><br>
                    <%= f.file_field :image %><br>
                </div>
                <%= f.submit '保存する', class: "btn btn-success" %><br>
                <%= link_to '投稿詳細ページへ', post_path(@post), class: "btn btn-dark mt-3" %>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">旅行投稿一覧</h1>
    </div>
    <div class="row mt-5 index-left w-100">
      <% @posts.each do |post| %>
        <div class="one-post col-sm-4 mb-3">
          <%= link_to post_path(post) do%>
            <p class="caption">ユーザ名</p>
            <% if post.image.attached?%>
              <%= image_tag post.image.variant(resize_to_limit: [300,200]) %><br>
            <% end %>
            <p class="caption"><%= post.location %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="cover-new">
    <div class="container d-flex flex-column align-items-center">
        <div class="row mt-5">
            <h1 class="font-weight-normal">旅行新規投稿</h1>
        </div>
        <div class="row mt-5">
            <%= form_with model: @post, local: true do |f| %>
                <div class="form-group mb-3">
                    <label class="form-label">【旅行先】</label>
                    <%= f.text_field :location ,class: "form-control" %>
                </div>
                <div class="form-group mb-3">
                    <label class="form-label">【感想】</label>
                    <%= f.text_area :text, rows: 10, class: "form-control" %>
                </div>
                <div class="form-group mb-3">
                    <label class="form-label">【画像】</label><br>
                    <%= f.file_field :image %>
                </div>
                <%= f.submit '投稿する',class: "btn btn-success" %>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="cover-show">
  <div class="container">
    <div class="row">
      <h1 class="font-weight-nomal mt-5 mb-5">旅行投稿詳細</h1>
    </div>
    <div class="d-block">
      <p class="caption">ユーザ名</p>
      <% if @post.image.attached?%>
        <%= image_tag @post.image.variant(resize_to_limit: [450, 350])%><br>
      <% end %>
      <p class="caption"><%= @post.location %></p>
      <h2>感想<h2>
      <p id="text"><%= @post.text %></p>
      <%= link_to '編集する', edit_post_path(@post.id), class: "btn btn-info mr-3" %>
      <%= link_to '削除する', post_path(@post.id),  data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: "btn btn-danger" %><br>
      <%= link_to '投稿一覧ページへ', posts_path, class: "btn btn-dark mt-3" %>
    </div>
  </div>
</div>